### ISSUE TITLE
Export TS declaration

### ISSUE THREAD

**Issue by StefanWerW** [vardius/react-peer-data#7]
Its simple, just add `declaration: true` to tsconfig
```
{
  "compilerOptions": {
...
    "declaration": true,
...
}
```

Otherwise we get this error: 
![image](https://user-images.githubusercontent.com/12717998/77530874-45969b00-6e92-11ea-8ada-aa4570cca359.png)

**Comment by vardius** [comment]
With this change during build there is following error:

`rpt2: options error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.`

**Comment by StefanWerW** [comment]
I'll have a look. I have seen you've merged the PR. Is the error solved?

**Comment by vardius** [comment]
I did small workaround for ts config in relation to test/build env

released new version which should have this issue fixed
https://github.com/vardius/react-peer-data/releases/tag/v1.0.8
https://www.npmjs.com/package/react-peer-data/v/1.0.8

Let me know if it works for you and we can close this issue

**Comment by vardius** [comment]
@StefanWerW any update ? did it worked for you as expected ?

**Comment by StefanWerW** [comment]
Sorry, could test. Busy week. Will try to do this week and share the results :)

BTW, let me say here how much I appreciate all your peer-data-* libraries. I've been reading alot of the source code, and it's really cool.

**Comment by vardius** [comment]
consider this solved. closing, reopen if still needs attention
